apiVersion: v1
kind: Secret
metadata:
  name: test-user-jwt
  labels:
    konghq.com/credential: jwt
  annotations:
    kubernetes.io/ingress.class: kong
type: Opaque
stringData:
  kongCredType: jwt
  key: mykey
  algorithm: HS256
  secret: supersecret