apiVersion: apps/v1
kind: Deployment
metadata:
  name: media-depl
spec:
  replicas: 1
  selector:
    matchLabels:
      app: media
  template:
    metadata:
      labels:
        app: media
    spec:
      containers:
        - name: media
          image: mohitrakh/pod-media:latest
          imagePullPolicy: Never
          ports:
            - containerPort: 5000
          env:
            - name: PORT
              value: "5000"
            - name: BASE_URL
              value: "http://localhost:8000"
