apiVersion: apps/v1
kind: Deployment
metadata:
  name: podcast-depl
spec:
  replicas: 1
  selector:
    matchLabels:
      app: podcast
  template:
    metadata:
      labels:
        app: podcast
    spec:
      containers:
        - name: podcast
          image: mohitrakh/podcast:latest
          imagePullPolicy: IfNotPresent
          ports:
            - containerPort: 5000
          env:
            - name: MONGO_URI
              value: "mongodb://podcast-mongo-srv:27017/podcast"
            - name: JWT_KEY
              valueFrom:
                secretKeyRef:
                  name: jwt-secret
                  key: JWT_KEY
            - name: PORT
              value: "5000"
            - name: BASE_URL
              value: "http://localhost:8000"
          readinessProbe:
            httpGet:
              path: /api/public/podcast/health
              port: 5000
            initialDelaySeconds: 5
            periodSeconds: 5
          
          livenessProbe:
            httpGet:
              path: /api/public/podcast/health
              port: 5000
            initialDelaySeconds: 10
            periodSeconds: 10
            